# Generated by Django 3.2 on 2021-04-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CarouselPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComboBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('product_description_pl', models.TextField()),
                ('product_description_en', models.TextField()),
                ('recommended', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cukiernia.category')),
            ],
        ),
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cukiernia.product')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProductJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ManyToManyField(to='cukiernia.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.BooleanField()),
                ('url', models.URLField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cukiernia.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='related_product_junction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cukiernia.relatedproductjunction'),
        ),
        migrations.CreateModel(
            name='ComboBoxValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('combo_box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cukiernia.combobox')),
            ],
        ),
        migrations.AddField(
            model_name='combobox',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cukiernia.product'),
        ),
    ]
