# Generated by Django 3.2 on 2021-04-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_product_junction_id',
        ),
    ]
