# Generated by Django 3.2 on 2021-04-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0002_remove_product_related_product_junction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedproductjunction',
            name='related',
        ),
        migrations.AddField(
            model_name='relatedproductjunction',
            name='related_first',
            field=models.ManyToManyField(related_name='related_first', to='cukiernia.Product'),
        ),
        migrations.AddField(
            model_name='relatedproductjunction',
            name='related_second',
            field=models.ManyToManyField(related_name='related_second', to='cukiernia.Product'),
        ),
    ]
