# Generated by Django 3.2 on 2021-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0003_auto_20210411_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselphoto',
            name='url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
