# Generated by Django 3.2 on 2021-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0004_auto_20210411_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselphoto',
            name='url',
            field=models.ImageField(upload_to='uploads/carousel/'),
        ),
    ]
