# Generated by Django 3.2 on 2021-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0006_alter_productphoto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='is_required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combobox',
            name='is_required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textbox',
            name='is_required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
