# Generated by Django 3.2 on 2021-04-13 08:02

import cukiernia.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0007_auto_20210413_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselphoto',
            name='url',
            field=models.ImageField(upload_to=cukiernia.helpers.RandomFileName('uploads/carousel/')),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='url',
            field=models.ImageField(upload_to=cukiernia.helpers.RandomFileName('uploads/products/')),
        ),
    ]
