# Generated by Django 3.2 on 2021-04-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0008_auto_20210413_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cukiernia.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textbox',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
