# Generated by Django 3.2 on 2021-04-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0009_auto_20210418_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='name',
            new_name='name_pl',
        ),
        migrations.RenameField(
            model_name='combobox',
            old_name='name',
            new_name='name_pl',
        ),
        migrations.RenameField(
            model_name='comboboxvalue',
            old_name='text',
            new_name='text_pl',
        ),
        migrations.RemoveField(
            model_name='textbox',
            name='name',
        ),
        migrations.AddField(
            model_name='calendar',
            name='name_en',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combobox',
            name='name_en',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comboboxvalue',
            name='text_en',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textbox',
            name='name_en',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textbox',
            name='name_pl',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
