# Generated by Django 3.2 on 2021-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0010_auto_20210418_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbox',
            name='max_length',
            field=models.IntegerField(default=255),
            preserve_default=False,
        ),
    ]
