# Generated by Django 3.1.8 on 2021-05-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0015_product_production_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='production_time',
        ),
    ]
