# Generated by Django 3.1.8 on 2021-05-12 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0016_remove_product_production_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandRetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_time', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cukiernia.product')),
            ],
        ),
        migrations.CreateModel(
            name='InstantRetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cukiernia.product')),
            ],
        ),
    ]
