# Generated by Django 3.1.8 on 2021-05-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0017_instantretail_ondemandretail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantretail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cukiernia.product', unique=True),
        ),
        migrations.AlterField(
            model_name='ondemandretail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cukiernia.product', unique=True),
        ),
    ]
