# Generated by Django 3.1.8 on 2021-05-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0018_auto_20210512_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboboxvalue',
            name='price_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('value_pl', models.CharField(max_length=50)),
                ('value_en', models.CharField(max_length=50)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cukiernia.order')),
            ],
        ),
    ]
