# Generated by Django 3.1.8 on 2021-05-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0020_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cukiernia.delivery'),
        ),
    ]
