# Generated by Django 3.1.8 on 2021-05-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0021_auto_20210512_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
