# Generated by Django 3.1.8 on 2021-05-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0022_decoration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cukiernia.product'),
            preserve_default=False,
        ),
    ]
