# Generated by Django 3.1.8 on 2021-05-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukiernia', '0023_decoration_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
